[package]
name = "mandelbrot"
version = "0.2.1"
authors = ["Jim Blandy <jimb@red-bean.com>"]
edition = "2021"

[dependencies]
image = "0.25"
num = "0.4"
atomic_chunks_mut = { git = "https://github.com/jimblandy/atomic-chunks-mut.git" }
