[package]
name = "mandelbrot"
version = "0.2.0"
authors = ["Jim Blandy <jimb@red-bean.com>"]

[dependencies]
num = "0.1.34"
image = "0.10.4"
crossbeam = "0.2.9"
atomic_chunks_mut = { git = "https://github.com/jimblandy/atomic-chunks-mut.git" }
